/**
 * swe-arena — typed replay of the committed SOLO-vs-SUPERVISOR head-to-head
 * artifacts (SWE-bench Verified, glm-5.2 both arms).
 *
 * MILESTONE 1: these types mirror the fixture files byte-for-byte semantics.
 * They are the proof-of-faithfulness layer: `reconcile.ts` + `analyze.ts`
 * must reproduce the reference `fixtures/analyze.py` output exactly (pinned in
 * `replay.test.mts`) before any typed execution path is built on top.
 */

/**
 * The fields of one SWE-bench Verified instance we actually consume from
 * `task-meta.json` (generated by the experiment's `load_meta.py` from
 * princeton-nlp/SWE-bench_Verified). `FAIL_TO_PASS` / `PASS_TO_PASS` are
 * JSON-encoded string arrays as shipped by the HF dataset — kept as raw
 * strings here; decode at the point of use.
 */
export interface SweInstance {
  instance_id: string
  repo: string
  base_commit: string
  problem_statement: string
  patch: string
  test_patch: string
  /** JSON-encoded string[] (raw HF dataset encoding). */
  FAIL_TO_PASS: string
  /** JSON-encoded string[] (raw HF dataset encoding). */
  PASS_TO_PASS: string
  version: string | null
  environment_setup_commit: string | null
}

/** Per-run opencode usage breakdown captured on the SOLO arm. */
export interface SoloUsage {
  steps: number
  in: number
  out: number
  reasoning: number
  cache_w: number
  cache_r: number
  max_ctx: number
  oc_cost: number
  total_io: number
}

/**
 * One paired row of `ledger.jsonl` — exactly the schema the experiment wrote.
 * `null` values are real telemetry gaps (e.g. `sup_spentTokens: null` when the
 * supervisor driver exited rc=3 mid-run), not absent data to be defaulted.
 */
export interface LedgerRow {
  iid: string
  solo_resolved: boolean
  sup_resolved: boolean
  solo_verify_pass: boolean
  sup_verify_pass: boolean
  solo_patch_lines: number
  sup_patch_lines: number
  solo_wall_s: number
  sup_wall_s: number
  solo_tokens: number
  solo_usage: SoloUsage
  sup_spentTokens: number | null
  sup_spentUsd: number | null
  sup_spawned: number
  /** Missing on rows written before the field was added (pallets__flask-5014). */
  sup_workers?: number
  sup_settled: number
  sup_subtasks: string[]
  sup_delivered: boolean | null
  /**
   * The fixture ledger observed only completed/running; the driver can also
   * settle failed/cancelled (M2 widened the union — the typed execution path
   * records those honestly instead of coercing them).
   */
  sup_status: 'completed' | 'running' | 'failed' | 'cancelled' | null
  sup_verdict: 'delivered' | 'no-winner' | 'best-effort' | null
  solo_oc_rc: number
  sup_driver_rc: number
  solo_patch: string
  sup_patch: string
  /** Free-form correction note (e.g. psf__requests-1766 sup re-judge). */
  _note?: string
}

/**
 * Tags carried by `rejudge.jsonl` rows. Gold-family tags grade the OFFICIAL
 * gold patch (calibrating the judge itself); final/my-reverify tags are the
 * personal authoritative re-judgements of arm patches that override the
 * automated ledger verdicts.
 */
export type RejudgeTag =
  | 'gold-control'
  | 'gold'
  | 'gold2'
  | 'solo-final'
  | 'sup-final'
  | 'solo-final2'
  | 'sup-final2'
  | 'my-reverify'

/** One row of `rejudge.jsonl`. `resolved: null` = the judge run failed to parse (inconclusive). */
export interface RejudgeRow {
  iid: string
  tag: RejudgeTag
  patch: string
  resolved: boolean | null
  score?: number
  secs?: number
  patch_bytes?: number
  error?: string
  raw?: string
}

/** Evolution-round labels: SUP2/3/4 = rematch.jsonl / rematch2.jsonl / rematch3.jsonl. */
export type RematchArm = 'SUP2' | 'SUP3' | 'SUP4'

/** One row of a rematch*.jsonl evolution round. */
export interface RematchRow {
  iid: string
  arm: RematchArm
  resolved: boolean
  verify_pass: boolean
  patch_lines: number
  wall_s: number
  spawned: number
  workers: number
  sup_status: 'completed' | 'running'
  sup_verdict: 'delivered' | 'no-winner' | 'best-effort' | null
  delivered: boolean | null
  spentTokens: number | null
}

/** Declarative arm identity for typed execution paths built on this module. */
export interface ArmSpec {
  name: string
  kind: 'solo' | 'supervisor'
  env: Record<string, string>
  provenance: { repo: string; commit: string }
}

/** One pre-registered holdout instance from `holdout.json`. */
export interface HoldoutEntry {
  iid: string
  repo: string
  gold_official_resolved: boolean
  verify_calibrated: boolean
  selected_at_commit: string
}

/**
 * The holdout registry: instances selected BEFORE any arm ran (see
 * `holdout-preregister.log`), each with its gold patch verified against the
 * calibrated judge. Only entries passing both checks are usable.
 */
export interface HoldoutRegistry {
  entries: HoldoutEntry[]
  /** Commit of the supervisor runtime (`loops`) at selection time. */
  selectedAtCommit: string
}

/** Per-instance supervisor worker-session spend from `worker-tokens.json`. */
export interface WorkerTokens {
  worker_sessions: number
  worker_tok: number
}
